"""EmerGNN thin adapter — implementation of :class:`BaselineModel`.

NOTE — paper-vs-port task formulation:
  * Original paper (Zhang et al., Nat Comp Sci 2023) on DrugBank does
    **multi-class** (predict-which-of-86-types, softmax margin loss,
    macro F1 / ACC / Cohen κ). The MULTI-CLASS task is in the parent
    paper; see ``baseline_multiclass.py`` for that variant.
  * THIS binary adapter is a ColdDDI-aligned simplification for
    cold-start S0/S1/S2 binary AUC/F1 evaluation. Negative samples are
    generated by drug replacement (ColdDDI protocol), NOT from the
    paper's multi-class formulation.

Wraps the verbatim research-repo modules
:mod:`baseline.emergnn.model` (the pure-PyTorch reimplementation
of EmerGNN — no torchdrug / torch_scatter required),
:mod:`baseline.emergnn.kg_builder` (KG → triplet table), and
:mod:`baseline.emergnn.morgan_features` (Morgan-FP entity feats).

The adapter is responsible for two bridges:

* :class:`data_utils.kg.KnowledgeGraph` → the legacy ``my_X_list``
  dict the source kg_builder consumes.
* :class:`data_utils.dataset.PairDataset` train/val/test rows → the
  per-pair head/tail entity indices the EmerGNN forward pass expects.

Like :class:`baseline.deepddi.DeepDDIBaseline`, this module is
the **template** for any KG-aware baseline: cast the KG once at fit
time, keep entity-id → index lookup as state, batch over
``DataFrame[drug_a_id, drug_b_id]`` for predict.
"""

from __future__ import annotations

import copy
import json
import pickle
import sys
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np
import pandas as pd
import sklearn  # noqa: F401  — kept so the manifest version export stays useful
import torch
from sklearn.metrics import roc_auc_score
from torch import optim
from torch.nn.functional import binary_cross_entropy_with_logits
from torch.optim.lr_scheduler import ReduceLROnPlateau

from baseline.base import BaselineModel, register, write_manifest
from baseline.emergnn._shared import (
    ensure_kg_setup_cache as _ensure_kg_setup_cache,
)
from baseline.emergnn.kg_builder import (
    N_BASE_REL,
    build_kg_from_kb,
    build_sparse_adj,
    edges_as_dense_lists,
)
from baseline.emergnn.kg_builder_merged import (
    build_kg_from_merged_parquet,
)
from baseline.emergnn.model import EmerGNN
from baseline.emergnn.morgan_features import compute_morgan_matrix
from baseline.emergnn.shuffle_utils import (
    build_edge_lists_from_triplets,
    shuffle_train,
)

if TYPE_CHECKING:
    from data_utils.dataset import PairDataset
    from data_utils.protocols import KnowledgeGraphProtocol


def _kg_to_kb_dict(kg: "KnowledgeGraphProtocol") -> dict[str, pd.DataFrame]:
    """Convert a :class:`KnowledgeGraph`-shaped object to the legacy
    ``my_X_list`` schema that :func:`build_kg_from_kb` expects."""
    required = ("enzymes", "targets", "transporters", "carriers", "pathways")
    missing = [a for a in required if not hasattr(kg, a)]
    if missing:
        raise TypeError(
            f"EmerGNN requires a knowledge graph with attributes "
            f"{required}; got {type(kg).__name__} (missing {missing})."
        )
    return {
        "my_enzyme_list": kg.enzymes,
        "my_target_list": kg.targets,
        "my_transporter_list": kg.transporters,
        "my_carrier_list": kg.carriers,
        "my_pathway_list": kg.pathways,
    }


def _drug_smiles_dict(train: "PairDataset") -> dict[str, str]:
    if train.drugs is None or "smiles" not in train.drugs.columns:
        raise ValueError(
            "EmerGNN requires `PairDataset.drugs` with a `smiles` column. "
            "Load via `from_release_dir` after Stage 1b, or pass a legacy "
            "bundle whose `extra['kb']` includes `my_drugs_list`."
        )
    return {
        str(row["drugbank_id"]): "" if pd.isna(row["smiles"]) else str(row["smiles"])
        for _, row in train.drugs[["drugbank_id", "smiles"]].iterrows()
    }


# DEPRECATED 2026-05-20: single-S2-mode binary baseline produced degenerate
# AUC=0.5 on test_s0/s1 under paper-faithful drugbank KG (see diagnostic at
# Code/runs/_diagnose/emergnn_s0s1_collapse.json). Replaced by the multimode
# wrapper now at baseline/emergnn/binary_cls/baseline.py (registered as "emergnn").
# Class kept here as historical record; NO LONGER REGISTERED, so importing
# this file does not collide with the new "emergnn" registry slot. Class
# also renamed to EmerGNNBaselineLegacyBuggy so anyone reading code sees
# the deprecation immediately.
class EmerGNNBaselineLegacyBuggy(BaselineModel):
    """EmerGNN: bidirectional attention message-passing on the DrugBank KG.

    .. deprecated:: 2026-05-20
       Single-S2-mode binary baseline; the paper-faithful multimode replacement
       at ``baseline/emergnn/binary_cls/baseline.py`` produced AUC 0.99 / 0.83 /
       0.75 on test_s0/s1/s2 versus this class's 0.50 / 0.50 / 0.74 on the
       same seed-42 setup. Kept only as historical record.
    """

    VERSION = "1.0"

    def __init__(
        self,
        *,
        n_dim: int = 64,
        length: int = 3,
        feat: str = "M",  # 'M' Morgan / 'E' learned
        learning_rate: float = 1e-3,
        batch_size: int = 32,
        # Paper hyperopt S1/S2 best = 100 epochs (evaluate.py:run_model
        # hardcoded override). CLAUDE.md §baseline-from-reproduction:
        # paper-tuned defaults must propagate to the baseline as well.
        n_epochs: int = 100,
        device: str = "auto",
        # KG source toggle:
        #   "drugbank" (default): use train.kg 5-bucket schema (legacy)
        #   "merged"            : use merged DrugBank+Hetionet+PrimeKG parquet,
        #                         requires `merged_kg_path` (path to edges parquet)
        backbone_kg_source: str = "drugbank",
        merged_kg_path: str | Path | None = None,
        merged_kg_blocklist: tuple[str, ...] = (),
        # Paper-faithful additions (CLAUDE.md §baseline-from-reproduction):
        # weight_decay matches paper hyperopt S1/S2 best (1e-8).
        # shuffle_train_mode preserves paper inductive design even though
        # paper's DrugBank task is multi-class — keeping the inductive
        # simulation helps cold-start binary too.
        weight_decay: float = 1e-8,
        shuffle_train_mode: str = "S2",
        shuffle_ratio: float = 0.8,
        # Training progress logging: print rolling-mean loss every N steps
        # (per CLAUDE.md 训练进度日志规范). Per-epoch summary always printed.
        log_step_every: int = 50,
        # Eval / save during training (per CLAUDE.md 训练中间 eval/save 规范,
        # HF Trainer style):
        eval_strategy: str = "epoch",   # "no" | "epoch" | "steps"
        eval_steps: int = 500,
        save_strategy: str = "no",      # "no" | "epoch" | "steps"
        save_steps: int = 500,
        save_total_limit: int = 3,
        load_best_model_at_end: bool = True,
        run_dir: str | Path | None = None,  # where intermediate checkpoints go
    ) -> None:
        self.n_dim = n_dim
        self.length = length
        self.feat = feat
        self.learning_rate = learning_rate
        self.batch_size = batch_size
        self.n_epochs = n_epochs
        self.device = self._resolve_device(device)
        self.backbone_kg_source = backbone_kg_source
        self.merged_kg_path = Path(merged_kg_path) if merged_kg_path is not None else None
        self.merged_kg_blocklist = tuple(merged_kg_blocklist)
        self.weight_decay = float(weight_decay)
        self.shuffle_train_mode = str(shuffle_train_mode)
        self.shuffle_ratio = float(shuffle_ratio)
        self.log_step_every = int(log_step_every)
        self.eval_strategy = eval_strategy
        self.eval_steps = int(eval_steps)
        self.save_strategy = save_strategy
        self.save_steps = int(save_steps)
        self.save_total_limit = int(save_total_limit)
        self.load_best_model_at_end = bool(load_best_model_at_end)
        self.run_dir = Path(run_dir) if run_dir is not None else None
        if self.backbone_kg_source not in {"drugbank", "merged"}:
            raise ValueError(f"unknown backbone_kg_source={self.backbone_kg_source!r}; expect 'drugbank' or 'merged'")
        if self.backbone_kg_source == "merged" and self.merged_kg_path is None:
            raise ValueError("backbone_kg_source='merged' requires merged_kg_path to be set")
        self._model: EmerGNN | None = None
        self._entity2id: dict[str, int] | None = None
        self._n_ent: int | None = None
        self._n_base_rel: int | None = None  # tracks N for save/load consistency
        self._edge_src: torch.Tensor | None = None
        self._edge_dst: torch.Tensor | None = None
        self._edge_rel: torch.Tensor | None = None

    @staticmethod
    def _resolve_device(d: str) -> str:
        if d == "auto":
            return "cuda" if torch.cuda.is_available() else "cpu"
        return d

    # ------------------------------------------------------------------
    # KG / feature setup (called by fit/load)
    # ------------------------------------------------------------------

    def _setup_graph(
        self,
        train: "PairDataset",
        kg: "KnowledgeGraphProtocol",
    ) -> tuple[np.ndarray, list[str]]:
        """Build entity vocab + edge tensors from a KG. Returns (morgan_matrix, drug_ids).

        Per CLAUDE.md §"Baseline 规范" §2 step 3: for the ``merged`` KG
        source, route through :func:`baseline.emergnn._shared.ensure_kg_setup_cache`
        — auto-detects existing ``_data/necessary/kg_setup__<hash>__mine.pkl``
        or auto-builds via subprocess. For the legacy ``drugbank`` 5-bucket
        source, fall back to in-memory build (input is a transient Python
        object with 5 DataFrames; cache key derivation is complex and not
        implemented yet).
        """
        # Drug pool union — required for both code paths.
        drug_ids: set[str] = set()
        for _name, df in train.splits.items():
            drug_ids.update(df["drug_a_id"].astype(str))
            drug_ids.update(df["drug_b_id"].astype(str))
        if self.backbone_kg_source == "drugbank" and hasattr(kg, "drug_ids"):
            # legacy KG path additionally unions kg.drug_ids (full DrugBank
            # pool) so 5-bucket edges to all 2061 drugs remain in vocab.
            drug_ids.update(kg.drug_ids)
        drug_id_list = sorted(drug_ids)

        if self.backbone_kg_source == "merged":
            # Cached path — CLAUDE.md §"Baseline 规范" §2 consumer pattern.
            cached = _ensure_kg_setup_cache(
                train,
                backbone_kg_source="merged",
                merged_kg_path=self.merged_kg_path,
                blocklist=self.merged_kg_blocklist,
            )
            self._entity2id = cached["entity2id"]
            self._n_ent = cached["n_ent"]
            self._n_base_rel = cached["n_base_rel"]
            self._kg_triplets = np.asarray(cached["kg_triplets"], dtype=np.int64)
            self._kg_entity_set = set(cached["kg_entity_set"])
            self._edge_src = torch.as_tensor(cached["edge_src"], dtype=torch.long)
            self._edge_dst = torch.as_tensor(cached["edge_dst"], dtype=torch.long)
            self._edge_rel = torch.as_tensor(cached["edge_rel"], dtype=torch.long)
            morgan_mat = np.asarray(cached["morgan_mat"], dtype=np.float32)
            missing = cached.get("missing_smiles", [])
            if missing:
                print(
                    f"[emergnn] {len(missing)} drugs lacked parseable SMILES "
                    f"and were zero-filled (from cache).",
                    file=sys.stderr,
                )
            return morgan_mat, cached.get("drug_id_list", drug_id_list)

        # Legacy in-memory path for ``backbone_kg_source="drugbank"`` (5-bucket
        # schema from train.kg). Caching not implemented because the
        # input is a transient Python object with 5 DataFrames; would
        # need DataFrame content hashing. The merged path covers
        # production runs; this path is for legacy/debug only.
        if self.backbone_kg_source != "drugbank":
            raise ValueError(f"unknown backbone_kg_source={self.backbone_kg_source!r}")

        print(
            f"[emergnn] backbone_kg_source='drugbank' (legacy 5-bucket) — using "
            f"in-memory _setup_graph; caching not implemented for this path.",
            file=sys.stderr,
        )
        kb = _kg_to_kb_dict(kg)
        kg_artifacts = build_kg_from_kb(kb, drug_id_list, keep_only_known_drugs=True)
        n_base_rel = N_BASE_REL  # 5

        self._entity2id = kg_artifacts["entity2id"]
        self._n_ent = kg_artifacts["n_ent"]
        self._n_base_rel = n_base_rel
        self._kg_triplets = np.asarray(kg_artifacts["triplets"], dtype=np.int64)
        if len(self._kg_triplets):
            self._kg_entity_set = set(
                np.unique(self._kg_triplets[:, :2]).astype(np.int64).tolist()
            )
        else:
            self._kg_entity_set = set()

        adj = build_sparse_adj(
            kg_artifacts["triplets"], kg_artifacts["n_ent"], n_base_rel
        )
        self._edge_src, self._edge_dst, self._edge_rel = edges_as_dense_lists(adj)

        smiles = _drug_smiles_dict(train)
        n_ent = kg_artifacts["n_ent"]
        morgan_mat = np.zeros((n_ent, 1024), dtype=np.float32)
        drug_only_mat, missing = compute_morgan_matrix(drug_id_list, smiles)
        for did, row in zip(drug_id_list, drug_only_mat):
            morgan_mat[self._entity2id[did]] = row
        if missing:
            print(
                f"[emergnn] {len(missing)} drugs lacked parseable SMILES "
                f"and were zero-filled.",
                file=sys.stderr,
            )
        return morgan_mat, drug_id_list

    def _pair_indices(self, pairs: pd.DataFrame) -> tuple[torch.Tensor, torch.Tensor]:
        if self._entity2id is None:
            raise RuntimeError("EmerGNNBaselineLegacyBuggy.fit() must be called before predict_proba.")
        head = pairs["drug_a_id"].astype(str).map(self._entity2id)
        tail = pairs["drug_b_id"].astype(str).map(self._entity2id)
        if head.isna().any() or tail.isna().any():
            unknown = sorted(set(
                pairs.loc[head.isna(), "drug_a_id"].astype(str)
            ) | set(
                pairs.loc[tail.isna(), "drug_b_id"].astype(str)
            ))[:5]
            raise ValueError(
                f"EmerGNN saw drug ids not in the trained entity vocab: {unknown}…"
            )
        return (
            torch.tensor(head.to_numpy(), dtype=torch.long),
            torch.tensor(tail.to_numpy(), dtype=torch.long),
        )

    def _edges_on_device(self):
        return (
            self._edge_src.to(self.device),
            self._edge_dst.to(self.device),
            self._edge_rel.to(self.device),
        )

    # ------------------------------------------------------------------
    # ABC surface
    # ------------------------------------------------------------------

    def fit(
        self,
        train: "PairDataset",
        val: "PairDataset | None" = None,
        *,
        kg: "KnowledgeGraphProtocol | None" = None,
    ) -> None:
        if kg is None:
            kg = train.kg
        morgan_mat, _drug_ids = self._setup_graph(train, kg)

        # Paper-faithful: expand n_base_rel by 1 to add a "DDI" relation slot
        # (used by per-epoch shuffle_train to inject positive DDI fact
        # triplets back into the KG with a dedicated relation embedding).
        # See CLAUDE.md §baseline-from-reproduction for rationale.
        n_kg_rel = self._n_base_rel
        n_base_rel_with_ddi = n_kg_rel + 1
        self._n_base_rel_with_ddi = n_base_rel_with_ddi

        self._model = EmerGNN(
            n_ent=self._n_ent,
            n_base_rel=n_base_rel_with_ddi,
            n_dim=self.n_dim,
            length=self.length,
            feat=self.feat,
            morgan_features=morgan_mat if self.feat == "M" else None,
        ).to(self.device)
        # Paper base_model.py: Adam(lr, weight_decay=lamb) + ReduceLROnPlateau
        opt = optim.Adam(
            self._model.parameters(),
            lr=self.learning_rate,
            weight_decay=self.weight_decay,
        )
        # Paper base_model.py steps ReduceLROnPlateau once per
        # ``epoch_per_test`` (=5) epochs with ``patience=10`` → effective
        # tolerance ≈ 50 raw epochs without improvement. We step every
        # epoch (simpler bookkeeping), so we scale ``patience`` by 5 to
        # preserve the same effective tolerance.
        scheduler = ReduceLROnPlateau(opt, mode="max", factor=0.1, patience=50)

        # Convert train positives to (entity_id_a, entity_id_b, dummy_ddi_rel)
        # int triplets — dummy_ddi_rel = n_kg_rel (a fresh slot just past
        # the existing KG relations). Used by shuffle_train below.
        pos_df = train.splits.train.copy()
        a_ids = pos_df["drug_a_id"].astype(str).map(self._entity2id)
        b_ids = pos_df["drug_b_id"].astype(str).map(self._entity2id)
        valid_mask = a_ids.notna() & b_ids.notna()
        if not valid_mask.all():
            print(
                f"[emergnn] dropping {(~valid_mask).sum()} train pos rows with unknown drugs",
                file=sys.stderr,
            )
        train_ddi_int = np.stack(
            [
                a_ids[valid_mask].astype(np.int64).to_numpy(),
                b_ids[valid_mask].astype(np.int64).to_numpy(),
                np.full(int(valid_mask.sum()), n_kg_rel, dtype=np.int64),
            ],
            axis=1,
        )

        # Static eval KG = train_ddi + base_kg (built once, used for val/test).
        eval_kg_triplets = np.concatenate([train_ddi_int, self._kg_triplets], axis=0)
        esrc, edst, erel = build_edge_lists_from_triplets(
            eval_kg_triplets, self._n_ent, n_base_rel_with_ddi
        )
        self._eval_edges = (
            torch.from_numpy(esrc).long().to(self.device),
            torch.from_numpy(edst).long().to(self.device),
            torch.from_numpy(erel).long().to(self.device),
        )

        rng = np.random.default_rng(0)

        pos = train.splits.train.copy()
        best_val_auc = -1.0
        best_state: dict | None = None

        # Training progress logger (per CLAUDE.md 训练进度/eval/save 规范)
        try:
            from my_code.utils.train_progress import TrainProgress
            from my_code.utils.checkpoint import rotate_checkpoints
        except ImportError:
            sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
            from my_code.utils.train_progress import TrainProgress
            from my_code.utils.checkpoint import rotate_checkpoints
        n_pos_plus_neg = 2 * len(pos)
        steps_per_epoch = (n_pos_plus_neg + self.batch_size - 1) // self.batch_size
        progress = TrainProgress(
            total_epochs=self.n_epochs,
            log_step_every=self.log_step_every,
            total_steps_per_epoch=steps_per_epoch,
            prefix="[emergnn] ",
            eval_strategy=self.eval_strategy,
            eval_steps=self.eval_steps,
            save_strategy=self.save_strategy,
            save_steps=self.save_steps,
        )

        ckpt_root = (self.run_dir / "checkpoints") if self.run_dir is not None else None

        def _eval_dict() -> dict:
            auc = self._validate(val) if val is not None else float("nan")
            return {"val_auc": auc}

        def _save_ckpt(tag: str) -> None:
            if ckpt_root is None:
                return
            ckpt_path = ckpt_root / f"checkpoint-{tag}"
            ckpt_path.mkdir(parents=True, exist_ok=True)
            self.save(ckpt_path)
            progress.log_save(str(ckpt_path), scope="step" if "step" in str(tag) else "epoch")
            rotate_checkpoints(ckpt_root, self.save_total_limit)

        for epoch in range(self.n_epochs):
            # ── Paper-faithful per-epoch shuffle_train ──────────────────
            # Pick which positives become this epoch's KG facts (fact_triplet)
            # vs which become prediction targets. Inductive simulation per
            # CLAUDE.md §baseline-from-reproduction.
            epoch_kg, train_pos_targets = shuffle_train(
                train_ddi_int,
                self._kg_triplets,
                self.shuffle_train_mode,
                ratio=self.shuffle_ratio,
                rng=rng,
                # Paper: process_files_kg unions all 3 KG splits when
                # populating ``ddi_in_kg``. We mirror that with the full
                # static KG entity set computed in _setup_graph().
                extra_kg_ent=self._kg_entity_set,
            )
            if len(train_pos_targets) == 0:
                print(
                    f"[emergnn] epoch {epoch+1}: 0 train targets after "
                    f"shuffle_train (mode={self.shuffle_train_mode}); skip",
                    flush=True,
                )
                continue
            # Build this epoch's KG edges
            esrc, edst, erel = build_edge_lists_from_triplets(
                epoch_kg, self._n_ent, n_base_rel_with_ddi
            )
            edge_src = torch.from_numpy(esrc).long().to(self.device)
            edge_dst = torch.from_numpy(edst).long().to(self.device)
            edge_rel = torch.from_numpy(erel).long().to(self.device)

            # Generate negatives matching this epoch's target positives.
            # ``regenerate=True`` forces fresh per-epoch sampling via
            # ``data_utils.negatives.build_train_negatives`` with sub-seed
            # ``base_seed + 1000 + epoch`` (deterministic, different each
            # epoch). Aligned with hdn_ddi / tiger / ssi_ddi / dsn_ddi for
            # cross-baseline fairness — see CLAUDE.md §"Baseline 规范" §4
            # case A "训练协议 must match across baselines".
            # We then down-sample to match the (smaller) target positive
            # count produced by shuffle_train this epoch.
            pre_neg = train.get_train_negatives(epoch, regenerate=True)
            n_target_pos = len(train_pos_targets)
            if len(pre_neg) >= n_target_pos:
                neg_idx = rng.choice(len(pre_neg), size=n_target_pos, replace=False)
                neg = pre_neg.iloc[neg_idx].reset_index(drop=True)
            else:
                neg = pre_neg

            # Build positives DataFrame from target rows (need drug ids, not
            # entity ids, since _pair_indices re-looks them up).
            id2entity = {v: k for k, v in self._entity2id.items()}
            pos_target_df = pd.DataFrame(
                {
                    "drug_a_id": [id2entity[int(h)] for h in train_pos_targets[:, 0]],
                    "drug_b_id": [id2entity[int(t)] for t in train_pos_targets[:, 1]],
                }
            )

            pairs_df = pd.concat(
                [
                    pos_target_df.assign(label=1),
                    neg[["drug_a_id", "drug_b_id"]].assign(label=0),
                ],
                ignore_index=True,
            ).sample(frac=1, random_state=epoch).reset_index(drop=True)

            self._model.train()
            progress.epoch_start(epoch)
            for start in range(0, len(pairs_df), self.batch_size):
                batch = pairs_df.iloc[start : start + self.batch_size]
                head, tail = self._pair_indices(batch)
                head = head.to(self.device)
                tail = tail.to(self.device)
                y = torch.tensor(
                    batch["label"].to_numpy(), dtype=torch.float32, device=self.device
                )
                opt.zero_grad(set_to_none=True)
                logits = self._model(head, tail, edge_src, edge_dst, edge_rel)
                # Paper base_model.py: loss = loss.sum() then backward
                # (NOT mean) — keeps gradient scale consistent with the
                # multi-class variant and the paper's training recipe.
                loss = binary_cross_entropy_with_logits(logits, y, reduction="sum")
                loss.backward()
                opt.step()
                progress.step(loss.item() / max(len(batch), 1))

                # mid-epoch eval + save
                if progress.should_eval_step() and val is not None:
                    self._model.eval()
                    metrics = _eval_dict()
                    self._model.train()
                    progress.log_eval(metrics, scope="step")
                    if metrics.get("val_auc", -1) > best_val_auc:
                        best_val_auc = metrics["val_auc"]
                        best_state = copy.deepcopy(self._model.state_dict())
                if progress.should_save_step():
                    _save_ckpt(f"step{progress.step_count}")

            # end-of-epoch eval + save
            extra: dict = {}
            if progress.should_eval_epoch() and val is not None:
                self._model.eval()
                metrics = _eval_dict()
                self._model.train()
                progress.log_eval(metrics, scope="epoch")
                extra.update(metrics)
                if metrics.get("val_auc", -1) > best_val_auc:
                    best_val_auc = metrics["val_auc"]
                    best_state = copy.deepcopy(self._model.state_dict())
                # Paper base_model.py: scheduler.step on primary val metric
                # (here we use val_auc since binary task; paper uses macro F1
                # for its multi-class task).
                scheduler.step(metrics.get("val_auc", 0.0))
            if progress.should_save_epoch():
                _save_ckpt(f"ep{epoch+1:03d}")
            progress.epoch_end(extra=extra if extra else None)

        if self.load_best_model_at_end and best_state is not None:
            self._model.load_state_dict(best_state)
            print(f"[emergnn] loaded best val_auc={best_val_auc:.4f} state", flush=True)

    @torch.no_grad()
    def _validate(self, val: "PairDataset") -> float:
        pos = val.splits.val_s2[["drug_a_id", "drug_b_id"]]
        neg = val.get_negatives("val_s2")[["drug_a_id", "drug_b_id"]]
        if len(pos) == 0 or len(neg) == 0:
            return float("nan")
        y_score = np.concatenate([self.predict_proba(pos), self.predict_proba(neg)])
        y_true = np.concatenate([np.ones(len(pos)), np.zeros(len(neg))])
        return float(roc_auc_score(y_true, y_score))

    @torch.no_grad()
    def predict_proba(
        self,
        pairs: pd.DataFrame,
        *,
        kg: "KnowledgeGraphProtocol | None" = None,
    ) -> np.ndarray:
        if self._model is None:
            raise RuntimeError("EmerGNNBaselineLegacyBuggy must be fitted (or loaded) before prediction.")
        # Use the static eval KG (= train_ddi + base_kg) when available
        # (set up in fit() per paper convention vKG = train_ddi + train_kg).
        # Falls back to base-KG-only after load() without re-fit.
        if hasattr(self, "_eval_edges") and self._eval_edges is not None:
            edge_src, edge_dst, edge_rel = self._eval_edges
        else:
            edge_src, edge_dst, edge_rel = self._edges_on_device()
        self._model.eval()
        out = np.empty(len(pairs), dtype=np.float32)
        for start in range(0, len(pairs), self.batch_size):
            batch = pairs.iloc[start : start + self.batch_size]
            head, tail = self._pair_indices(batch)
            head = head.to(self.device)
            tail = tail.to(self.device)
            logits = self._model(head, tail, edge_src, edge_dst, edge_rel)
            probs = torch.sigmoid(logits).detach().cpu().numpy()
            out[start : start + len(batch)] = probs
        return out

    def save(self, path: "Path | str") -> None:
        if self._model is None or self._entity2id is None:
            raise RuntimeError("Nothing to save; call fit() first.")
        out = Path(path)
        out.mkdir(parents=True, exist_ok=True)
        torch.save(self._model.state_dict(), out / "model.pt")
        # ``_n_base_rel_with_ddi`` (= kg rel + 1) is what the model was
        # actually built with; falling back to the raw KG count would
        # corrupt load() with a shape mismatch on Wr.
        n_base_rel_save = int(
            getattr(self, "_n_base_rel_with_ddi", None) or self._n_base_rel
        )
        # Persist eval-edge tensors (CPU numpy) so predict_proba after
        # load() uses the paper's vKG = train_ddi + base_kg, not just
        # base KG.
        eval_edges_np = None
        if getattr(self, "_eval_edges", None) is not None:
            eval_edges_np = {
                "src": self._eval_edges[0].detach().cpu().numpy(),
                "dst": self._eval_edges[1].detach().cpu().numpy(),
                "rel": self._eval_edges[2].detach().cpu().numpy(),
            }
        with (out / "graph.pkl").open("wb") as f:
            pickle.dump(
                {
                    "entity2id": self._entity2id,
                    "n_ent": self._n_ent,
                    "edge_src": self._edge_src,
                    "edge_dst": self._edge_dst,
                    "edge_rel": self._edge_rel,
                    "morgan_features": (
                        self._model.ent_feat.cpu().numpy() if self.feat == "M" else None
                    ),
                    "n_base_rel_with_ddi": n_base_rel_save,
                    "n_base_rel_kg": int(self._n_base_rel),
                    "eval_edges": eval_edges_np,
                },
                f,
            )
        write_manifest(
            out,
            baseline_name=self.name,
            extra={
                "version": self.VERSION,
                "hyperparameters": {
                    "n_dim": self.n_dim,
                    "length": self.length,
                    "feat": self.feat,
                    "learning_rate": self.learning_rate,
                    "batch_size": self.batch_size,
                    "n_epochs": self.n_epochs,
                },
                "environment": {
                    "torch_version": torch.__version__,
                    "sklearn_version": sklearn.__version__,
                },
                "graph_metadata": {
                    "n_ent": int(self._n_ent),
                    "n_base_rel": int(self._n_base_rel),
                    "n_base_rel_with_ddi": n_base_rel_save,
                    "backbone_kg_source": self.backbone_kg_source,
                },
            },
        )

    @classmethod
    def load(cls, path: "Path | str") -> "EmerGNNBaselineLegacyBuggy":
        p = Path(path)
        manifest = json.loads((p / "manifest.json").read_text())
        hparams = manifest.get("hyperparameters", {})
        inst = cls(**hparams)
        with (p / "graph.pkl").open("rb") as f:
            graph = pickle.load(f)
        inst._entity2id = graph["entity2id"]
        inst._n_ent = graph["n_ent"]
        inst._edge_src = graph["edge_src"]
        inst._edge_dst = graph["edge_dst"]
        inst._edge_rel = graph["edge_rel"]
        # KG-only relation count (used by setup helpers); fall back to
        # legacy N_BASE_REL=5 for pre-fix checkpoints.
        n_base_rel_kg = (
            graph.get("n_base_rel_kg")
            or manifest.get("graph_metadata", {}).get("n_base_rel")
            or N_BASE_REL
        )
        inst._n_base_rel = int(n_base_rel_kg)
        # Expanded relation count actually used to build the model.
        n_base_rel_with_ddi = (
            graph.get("n_base_rel_with_ddi")
            or manifest.get("graph_metadata", {}).get("n_base_rel_with_ddi")
            or (int(n_base_rel_kg) + 1)
        )
        inst._n_base_rel_with_ddi = int(n_base_rel_with_ddi)
        morgan = graph.get("morgan_features")
        inst._model = EmerGNN(
            n_ent=inst._n_ent,
            n_base_rel=int(n_base_rel_with_ddi),
            n_dim=inst.n_dim,
            length=inst.length,
            feat=inst.feat,
            morgan_features=morgan,
        ).to(inst.device)
        inst._model.load_state_dict(torch.load(p / "model.pt", map_location=inst.device))
        inst._model.eval()
        # Restore eval-edge tensors so predict_proba uses paper's vKG.
        eval_edges = graph.get("eval_edges")
        if eval_edges is not None:
            inst._eval_edges = (
                torch.from_numpy(eval_edges["src"]).long().to(inst.device),
                torch.from_numpy(eval_edges["dst"]).long().to(inst.device),
                torch.from_numpy(eval_edges["rel"]).long().to(inst.device),
            )
        else:
            inst._eval_edges = None
        return inst
